menu:
- {name: 'home', url: '/'}
- {name: 'research', url: '/research'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/hyunso-christy-oh'}

contacts:
- {name: 'Hyunso Christy Oh', title: 'PhD Candidate', department: 'Political Science', institution: 'Ohio State University', institution_address: 'Derby Hall, 154 N Oval Mall, Columbus, OH 43210', phone: 'XX', email: 'oh.663 [at] osu.edu', office: 'XX', image: 'assets/img/contact.jpg'}
